In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
35   74    Male     Poor    School       Yes
30   73    Male  Average        UG        No
2    70  Female     Good        PG        No
41   23    Male     Good        PG       Yes
21   32    Male  Average        PG        No

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.3,random_state=0)
x_train.shape, x_test.shape

((35, 2), (15, 2))

In [7]:
x_train

     review education
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [10]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
x_train = oe.transform(x_train)

In [12]:
x_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [13]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [14]:
# !pip install LableEncoder

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()

In [17]:
le.fit(y_train)

LabelEncoder()

In [18]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [19]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [20]:
y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [21]:
y_test

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0])

ONE HOT ENCODING

In [22]:
import pandas as pd 
import numpy as np

In [23]:
dff = pd.read_csv('used_cars_data.csv')

In [24]:
dff.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [25]:
dff.drop('S.No.',axis=1)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [26]:
dff.drop('New_Price',axis=1)
dff.drop('Mileage',axis=1)
dff.drop('Engine',axis=1)
dff.drop('Power',axis=1)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,5.0,NaN,NaN

In [27]:
dff.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [28]:
dff['Name'].value_counts()

Name
Mahindra XUV500 W8 2WD                  55
Maruti Swift VDI                        49
Maruti Swift Dzire VDI                  42
Honda City 1.5 S MT                     39
Maruti Swift VDI BSIV                   37
                                        ..
Chevrolet Beat LT Option                 1
Skoda Rapid 1.6 MPI AT Elegance Plus     1
Ford EcoSport 1.5 TDCi Ambiente          1
Hyundai i10 Magna 1.1 iTech SE           1
Hyundai Elite i20 Magna Plus             1
Name: count, Length: 2041, dtype: int64

In [29]:
dff.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [30]:
dff['Name'].nunique()

2041

In [31]:
pd.get_dummies(dff,columns=['Fuel_Type','Owner_Type'])

,S.No.,Name,Location,Year,Kilometers_Driven,Transmission,Mileage,Engine,Power,Seats,...,Price,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,Manual,26.6 km/kg,998 CC,58.16 bhp,5.0,...,1.75,True,False,False,False,False,True,False,False,False
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Manual,19.67 kmpl,1582 CC,126.2 bhp,5.0,...,12.50,False,True,False,False,False,True,False,False,False
2,2,Honda Jazz V,Chennai,2011,46000,Manual,18.2 kmpl,1199 CC,88.7 bhp,5.0,...,4.50,False,False,False,False,True,True,False,False,False
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Manual,20.77 kmpl,1248 CC,88.76 bhp,7.0,...,6.00,False,True,False,False,False,True,False,False,False
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Automatic,15.2 kmpl,1968 CC,140.8 bhp,5.0,...,17.74,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Manual,20.54 kmpl,1598 CC,103.6 bhp,5.0,...,NaN,False,True,False,False,False,True,False,False,False
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Automatic,17.21 kmpl,1197 CC,103.6 bhp,5.0,...,NaN,False,False,False,False,True,True,False,False,False
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Manual,23.08 kmpl,1461 CC,63.1 bhp,5.0,...,NaN,False,True,False,False,False,True,False,False,False
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Automatic,17.2 kmpl,1197 CC,103.6 bhp,5.0,...,NaN,False,False,False,False,True,False,False,False,True
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Automatic,10.0 kmpl,2148 CC,170 bhp,5.0,...,NaN,False,True,False,False,False,True,False,False,False

In [32]:
pd.get_dummies(dff,columns=['Fuel_Type','Owner_Type'],drop_first = True)

,S.No.,Name,Location,Year,Kilometers_Driven,Transmission,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,Manual,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,False,False,False,False,False,False,False
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Manual,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,True,False,False,False,False,False,False
2,2,Honda Jazz V,Chennai,2011,46000,Manual,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,False,False,False,True,False,False,False
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Manual,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,True,False,False,False,False,False,False
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Automatic,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Manual,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN,True,False,False,False,False,False,False
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Automatic,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN,False,False,False,True,False,False,False
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Manual,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN,True,False,False,False,False,False,False
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Automatic,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN,False,False,False,True,False,False,True
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Automatic,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN,True,False,False,False,False,False,False

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(dff.iloc[:,0:10],dff.iloc[:,-1],test_size=0.3,random_state=0)
x_train.shape, x_test.shape

((5077, 10), (2176, 10))

In [34]:
from sklearn.preprocessing import OneHotEncoder

In [35]:
ohe = OneHotEncoder(drop='first',dtype=np.int32)

In [36]:
x_train_new = ohe.fit_transform(x_train[['Fuel_Type','Owner_Type']]).toarray()

In [37]:
x_test_new = ohe.fit_transform(x_test[['Fuel_Type','Owner_Type']]).toarray()

In [38]:
x_train_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [39]:
x_train_new.shape

(5077, 7)

In [40]:
np.hstack((x_train[['Name','Kilometers_Driven']].values,x_train_new))

array([['Honda City i VTEC CVT VX', 39822, 0, ..., 0, 0, 0],
       ['Ford Figo Aspire 1.2 Ti-VCT Ambiente', 29875, 0, ..., 0, 0, 0],
       ['BMW 3 Series 320d', 25000, 1, ..., 0, 0, 0],
       ...,
       ['Mahindra Scorpio VLX', 62000, 1, ..., 0, 0, 0],
       ['Hyundai Verna CRDi 1.6 SX Option', 50000, 1, ..., 0, 0, 0],
       ['Maruti Swift Dzire ZDI', 83000, 1, ..., 0, 0, 0]], dtype=object)

In [41]:
dff['Name'].value_counts()

Name
Mahindra XUV500 W8 2WD                  55
Maruti Swift VDI                        49
Maruti Swift Dzire VDI                  42
Honda City 1.5 S MT                     39
Maruti Swift VDI BSIV                   37
                                        ..
Chevrolet Beat LT Option                 1
Skoda Rapid 1.6 MPI AT Elegance Plus     1
Ford EcoSport 1.5 TDCi Ambiente          1
Hyundai i10 Magna 1.1 iTech SE           1
Hyundai Elite i20 Magna Plus             1
Name: count, Length: 2041, dtype: int64

In [42]:
counts = dff['Name'].value_counts()

In [43]:
dff['Name'].nunique()
threshold =36

In [44]:
repl =counts[counts <= threshold].index

In [45]:
pd.get_dummies(dff['Name'].replace(repl,'uncommon'))

,Honda City 1.5 S MT,Mahindra XUV500 W8 2WD,Maruti Swift Dzire VDI,Maruti Swift VDI,Maruti Swift VDI BSIV,uncommon
0,False,False,False,False,False,True
1,False,False,False,False,False,True
2,False,False,False,False,False,True
3,False,False,False,False,False,True
4,False,False,False,False,False,True
...,...,...,...,...,...,...
7248,False,False,False,False,False,True
7249,False,False,False,False,False,True
7250,False,False,False,False,False,True
7251,False,False,False,False,False,True
7252,False,False,False,False,False,True

COLUMN TRANSFORMER

In [51]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [53]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['Name']),
    ('tnf2',OrdinalEncoder(categories=[['Owner_Type','Fuel_Type']]),['Name']),
    ('tnf3',OneHotEncoder(drop='first'),['Owner_Type','Fuel_Type']),
],remainder='passthrough')

In [55]:
transformer.transform(x_test).shape

NotFittedError: This ColumnTransformer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.